--- 
- hosts: myserver 
  become: yes
  tasks:
   - name: i want to install web server on ubantu node
     apt: 
      name: apache2
      state: present 
     when: ansible_os_family =="Debian" 

   - name: i want to install web server on RedHat node
     yum:
      name: httpd
      state: present
     when: ansible_os_family =="RedHat"  

   - name: i want to start my webserver on RedHat ansible node
     service:
         name: httpd
         state: started
     when: ansible_os_family =="RedHat"